// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRRxRotBdLrlupygTSOMvEeHVWWm4q0Zo',
    appId: '1:169949925377:web:b213cfab1affc38fabb000',
    messagingSenderId: '169949925377',
    projectId: 'laza-shop-app-9af04',
    authDomain: 'laza-shop-app-9af04.firebaseapp.com',
    storageBucket: 'laza-shop-app-9af04.firebasestorage.app',
    measurementId: 'G-4KN55L6M6R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYjSP2WmowkRU8i6kv_Y9BHy5uu-lQRnc',
    appId: '1:169949925377:android:a4108d20f3e8804babb000',
    messagingSenderId: '169949925377',
    projectId: 'laza-shop-app-9af04',
    storageBucket: 'laza-shop-app-9af04.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzx9xajx0Jxbju_RPEOQxSFGUvW5YQMas',
    appId: '1:169949925377:ios:f528ceedf47d841fabb000',
    messagingSenderId: '169949925377',
    projectId: 'laza-shop-app-9af04',
    storageBucket: 'laza-shop-app-9af04.firebasestorage.app',
    iosBundleId: 'com.example.lazaShopFirebaseApp',
  );
}
